#! /bin/sh

# this is specific to my (ben's) machine.
# You will have to plug in the appropriate paths
# on your own system.

# all the environment stuffs

# this will all have to change
CLANG=/Users/ben/llvm/build/bin/clang
CHECKER=alpha.unix.LockSetChecker
INCLUDE_FILE=/Users/ben/llvm/tools/clang/lockset/include.dirs
SUB_SCRIPT=/Users/ben/llvm/tools/clang/lockset/thread_func_rename.py

# get clang include
INCLUDE=$(cat $INCLUDE_FILE)

# exit if any command fails
set -e

if [ -z "$1" ]; then
    echo "USAGE: lockset-analyzer [-html] <input file>"
    exit
fi

# set the input file
if [ "$1" == "-html" ]; then
    FILE=$2
else
    FILE=$1
fi

# copy target file to tmp directory
TMP_DIR=$(mktemp -d)
cp $FILE $TMP_DIR
TMP_FILE=$(basename $FILE)

# run python script on file in tmp dir
python $SUB_SCRIPT $TMP_DIR/$TMP_FILE > /dev/null
# format the output of the script and stream
# it back to the original copied file
indent -di1 $TMP_DIR/new_$TMP_FILE $TMP_DIR/$TMP_FILE
# remove output of python script
rm -f $TMP_DIR/new_$TMP_FILE

if [ "$1" == "-html" ]; then
    # check file, open resulting the html
    $CLANG -o $TMP_DIR $TMP_DIR/$TMP_FILE --analyze -Xanalyzer -analyzer-output=html -Xanalyzer \
    -analyzer-checker=$CHECKER $INCLUDE 2>/dev/null 1>&2
    # open html if it exists
    if ls $TMP_DIR/*.html 1> /dev/null 2>&1; then
        echo "Race condition found!"
        FNAME=$(basename $(echo $TMP_DIR/*.html))
        #open $TMP_DIR/*.html
        cp $TMP_DIR/$FNAME $FNAME
        rm -f $TMP_DIR/$TMP_FILE
    else
        rm -rf $TMP_DIR
    fi
else
    # otherwise just stick with text output
    $CLANG $TMP_DIR/$TMP_FILE --analyze -Xanalyzer -analyzer-output=text -Xanalyzer \
    -analyzer-checker=$CHECKER $INCLUDE
    rm -rf $TMP_DIR
fi
